version: '3'
services:
  app:
    build: .
    ports:
      - "${PORT}:5007"
    environment:
      - DATA_DIR=${DATA_DIR}
      - SERVER_URL=${SERVER_URL}
      - PASSWORD=${PASSWORD}
      - SYNC_ID=${SYNC_ID}
    volumes:
      - ./data:/usr/src/app/data