version: '3'
services:
  app:
    build: .
    ports:
      - "5007:5007"
    environment:
      - DATA_DIR=${DATA_DIR}
      - SERVER_URL=${SERVER_URL}
      - PASSWORD=${PASSWORD}
      - BUDGET_ID=${BUDGET_ID}
    volumes:
      - ./data:/usr/src/app/data